### ISSUE TITLE
Auth server for BitBucket client is not specified

### ISSUE THREAD

**Issue by aku** [bitsbeats/drone-tree-config#11]
It seems that p.authClient in scm.go:23 is never initialized which causes a connection error

**Comment by foosinn** [comment]
From a quick look, the variable should come from env var `AUTH_SERVER`

**Comment by aku** [comment]
I guess if I select a certain SCM provider then there should be some default value for it. It would be strange to provide GitHub\BitBucket endpoint manually. I will check later if providing value for this variable fixes the problem with the connection.

**Comment by foosinn** [comment]
Im not sure how bitbucket works. Github works with the token on its on, since its the default method (and how we use it)

Let me now if the bugfix works (docker image bitsbeats/drone-tree-config:issue10), afterwards i can create a new release.

**Comment by foosinn** [comment]
Update, the Variable is now called `BITBUCKET_AUTH_SERVER`

**Comment by aku** [comment]
I've managed to configure the plugin by setting these environment variables in my docker-compose config:

-       - SERVER=https://api.bitbucket.org
-       - BITBUCKET_AUTH_SERVER=https://bitbucket.org

I think there should be separate variables like BITBUCKET_API_SERVER and BITBUCKET_AUTH_SERVER with proper default values to avoid confusion. Currently, it is not clear what values need to be set. 

I propose to introduce new variables to specify an SCM explicitly.  Then we can customize the selected SCM provider by setting additional params

**Comment by foosinn** [comment]
Was fixed with a41836bbd4ddba9fe818d1b1acac547187df6e0f
