### ISSUE TITLE
Add support for root folder files changing - trigger multiple pipelines

### ISSUE THREAD

**Issue by gevalter** [bitsbeats/drone-tree-config#18]
Hey, so far this plugin supports a simple logic - editing files within a folder runs the folder drone file.

But what if for example you have a python monorepo with a shared requirements.txt located in the repo root folder, and when it changes - you need all / multiple pipelines to run.

I know its an advanced feature to ask, i'm willing to help - just need your opinion @foosinn of how you think we can implement this, I think it's very useful feature for everyone.

**Comment by foosinn** [comment]
Hey,

a simple solution is to put more complex drone files futher up in the folder tree.

You could also write a pipeline in a specific directory that handles the required tasks. The other projects can link the file.

Currently there is no dependency solving embedded, also i think it's hard to implement without introducing custom fields into drones configuration

**Comment by gevalter** [comment]
Yea you probably right - thought about that and this use-case can be done in many other workarounds. closing this issue
