### ISSUE TITLE
How to use it on k8s

### ISSUE THREAD

**Issue by Hanggi** [bitsbeats/drone-tree-config#21]
I am using drone on k8s with kube-runner.

Do you have any tutorial using drone-tree-config on k8s?

Thank you

**Comment by Hanggi** [comment]
I already done, Thank you.

**Comment by manvinderr21** [comment]
I wanted to know how to add this extension to the already running drone setup. I had installed the drone using [helmchart](https://github.com/helm/charts/tree/master/stable/drone).
