### ISSUE TITLE
Rate limit hit

### ISSUE THREAD

**Issue by jlehtimaki** [bitsbeats/drone-tree-config#34]
What's the purpose of checking .drone.yml (or some other file) from every folder?
Can't it be just checked based on file listing from the API?

We are getting rate limit errors with monorepos since it tries to get Drone config file from every sub folder there is.

**Comment by foosinn** [comment]
I don't think there is a file listing for all directories as a single api-call. As workaround you can look into the `maxdepth`, `allow_list_file` and `consider_file` options.
