### ISSUE TITLE
Multiple commits

### ISSUE THREAD

**Issue by gevalter** [bitsbeats/drone-tree-config#7]
Hey guys, your plugin worked great for me until one of our programmers did the following use case: 
- changed folder A, then git commit
- changed folder B, then git commit
- changed folder C, then git commit 
- git push to branch - Drone built only folder C

The plugin suppose to go over all commits or only the last one?

**Comment by foosinn** [comment]
Drone does not always provide a last commit. Was the branch created with the push?

When drone provides no last build, drone-tree-config asumes just the last one. If you open a pull request the tests should be fine.

**Comment by gevalter** [comment]
Yes, the branch was created with the push after the last commit. And you are right, pull request & Merge builds do solve the problem but we do some test on the branch level before pushing to master. 

Maybe if I change this part to take the master branch as the before variable it would work? Or you think it will break something else?

`		// use diff to get changed files
		before := req.Build.Before
		if before == "0000000000000000000000000000000000000000" || before == "" {
			before = fmt.Sprintf("%s~1", req.Build.After)
		}
		var err error
		changedFiles, err = req.Client.ChangedFilesInDiff(ctx, before, req.Build.After)`

**Comment by foosinn** [comment]
i do not think its save to assume that the default branch is master.

also as far as i remember there where at least occasions where this happened
* new branches
* build restarts

currently i do not have the time  for a full test setup. can you investigate further?

**Comment by gevalter** [comment]
Hey, I found the bug and fixed it for our use case, i also edit the tests module, added the values needed for my solution to work, but i cannot open a pull request for this repo.

The problem was for builds triggered from push event, there was a git-diff between the last commit and the one before, that is wrong - when you push to remote branch in a multi branch environment - sometimes you have more than 1 commit.

scm.go:
`	} else {
		// use diff to get changed files
		before := req.Build.Before
		if before == "0000000000000000000000000000000000000000" || before == "" {
			before = fmt.Sprintf("%s~1", req.Build.After)
		}`

There are 2 cases -
1. New branch - condition is true, the "before" variable is populated with the last commit with a suffix of "~1", (which i don't understand why you inserted the suffix), and the "after" variable is also the last commit.
2. Existing branch - condition is false,  the "before" variable is populated with the commit before the push event and the "after" variable is also the last commit.

Please give me permissions to PR this repo, thank you!

**Comment by foosinn** [comment]
PR has been merged.
